
name: Build and deploy site

on: [push]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.30.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: ./scripts/render.ts

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "codebaser"
          entrypoint: ./scripts/prod.ts
          root: docs
          import-map: ./import_map.json
